name: teams-players-cron
on:
  schedule:
    - cron: '48 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call teams API route
        run: |
          curl --request GET \
          --url 'https://player-grid.vercel.app/api/cron/teams' \
      - name: Call teamPlayers API route
        run: |
          curl --request GET \
          --url 'https://player-grid.vercel.app/api/cron/teamPlayers' \
